parallel jobs

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -14,8 +14,7 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
+  bumps:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
@@ -51,53 +50,9 @@ jobs:
           python3 -m pip install -r requirements.txt
           conan config install https://github.com/conan-io/conan-extensions.git
 
-      # Runs a single command using the runners shell
       - name: Export all versions
         run: conan cci:export-all-versions --path recipes/
         working-directory: conan-center-index
-
-      - name: Check dependencies status
-        run: |
-          echo "::debug::Creating pages"
-          mkdir -p ../../pages
-          echo "::debug::Creating outfile"
-          outfile=../../pages/dependencies_maintenance_status.md
-          echo "| Recipe | Unmaintained dependencies |" > $outfile
-          echo "| ------ | ------------------------- |" >> $outfile
-          echo "::debug::Iterating recipes"
-          for d in */*/
-          do
-            if [[ $(conan inspect ${d} 2>/dev/null | grep '^deprecated:') ]]
-            then
-              echo "skipping ${d} because it is deprecated"
-              continue
-            fi
-            echo "::debug::recipe $d"
-            msg=""
-            for r in $(python ../../scan_for_non_maintained_dependencies.py $d/conanfile.py)
-            do
-              echo "::debug::dependency $r"
-              r_path=$(conan cache path $r 2>/dev/null || true)
-              echo "::debug::path $r_path"
-              if [[ -z "$r_path" ]]
-              then
-                echo "::warning  ::recipe $d depends on $r which is not maintained"
-                msg+="$r, "
-              elif [[ $(conan inspect $r_path 2>/dev/null | grep '^deprecated:') ]]
-              then
-                echo "::warning  ::recipe $d depends on $r which is deprecated"
-                msg+="$r, "
-              fi
-              echo "::debug::finish dependency"
-            done
-            if [[ ! -z "$msg" ]]
-            then
-              echo "::debug::appending to outfile $d $msg"
-              echo "| $d | ${msg::-2} |" >> $outfile
-            fi
-            echo "::debug::Finish recipe"
-          done
-        working-directory: conan-center-index/recipes
 
       - name: Clean branches
         run: |
@@ -188,13 +143,117 @@ jobs:
             echo "::endgroup::"
           done
         working-directory: conan-center-index/recipes
+      - uses: actions/upload-artifact@v3
+        with:
+          name: my-artifact
+          path: pages
+
+
+  status:
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Checkout CCI
+        uses: actions/checkout@v4
+        with:
+          repository: conan-io/conan-center-index
+          path: conan-center-index
+          token: ${{ secrets.COMMIT_TOKEN }}
+
+      - uses: actions/setup-python@v4
+        with:
+          python-version: "3.11"
+          cache: 'pip' # caching pip dependencies
+      - run: |
+          python3 -m pip install -r requirements.txt
+          conan config install https://github.com/conan-io/conan-extensions.git
+
+      - name: Remove deprecated recipes
+        run: |
+          for p in */
+          do
+            echo "::debug::Enterring package $p"
+            cd $p
+            for d in */
+            do
+              echo "::debug::Enterring folder $d"
+              code=0
+              conan inspect $d 1>output 2>/dev/null || code=$?
+              if [[ $code -ne 0 || $( grep '^deprecated:' output) ]]
+              then
+                echo "removing $p$d because it is deprecated"
+                echo "::debug::code: $code"
+                echo "::debug::$(<output)"
+                rm -r $d
+                yq -i "del(.versions[] | select(.folder == \"${d::-1}\"))" config.yml || echo "::error::Could not remove $d from $p"
+              fi
+              rm output
+            done
+            cd ..
+          done
+        working-directory: conan-center-index/recipes
+
+      - name: Export all versions
+        run: conan cci:export-all-versions --path recipes/
+        working-directory: conan-center-index
+
+      - name: Check dependencies status
+        run: |
+          echo "::debug::Creating pages"
+          mkdir -p ../../pages
+          echo "::debug::Creating outfile"
+          outfile=../../pages/dependencies_maintenance_status.md
+          echo "| Recipe | Unmaintained dependencies |" > $outfile
+          echo "| ------ | ------------------------- |" >> $outfile
+          echo "::debug::Iterating recipes"
+          for d in */*/
+          do
+            echo "::debug::recipe $d"
+            msg=""
+            for r in $(python ../../scan_for_non_maintained_dependencies.py $d/conanfile.py)
+            do
+              echo "::debug::dependency $r"
+              r_path=$(conan cache path $r 2>/dev/null || true)
+              echo "::debug::path $r_path"
+              if [[ -z "$r_path" ]]
+              then
+                echo "::warning  ::recipe $d depends on $r which is not maintained"
+                msg+="$r, "
+              fi
+              echo "::debug::finish dependency"
+            done
+            if [[ ! -z "$msg" ]]
+            then
+              echo "::debug::appending to outfile $d $msg"
+              echo "| $d | ${msg::-2} |" >> $outfile
+            fi
+            echo "::debug::Finish recipe"
+          done
+        working-directory: conan-center-index/recipes
+
+      - uses: actions/upload-artifact@v3
+        with:
+          name: my-artifact
+          path: pages
+
+  Gather_Results:
+    name: Gather results
+    needs: [bumps, status]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/download-artifact@v3
+        with:
+          name: my-artifact
 
       - name: Setup Pages
         uses: actions/configure-pages@v3
       - name: Build with Jekyll
         uses: actions/jekyll-build-pages@v1
         with:
-          source: ./pages
           destination: ./_site
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v2
@@ -211,7 +270,7 @@ jobs:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
-    needs: build
+    needs: Gather_Results
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
